CREATE TABLE hotels(
   hotel_id            INTEGER  NOT NULL PRIMARY KEY 
  ,name                VARCHAR(255) NOT NULL
  ,rating              NUMERIC(3,1) NOT NULL
  ,description         VARCHAR(8191) NOT NULL
  ,cancellation_policy VARCHAR(1024) NOT NULL
  ,phone               VARCHAR(31) NOT NULL
  ,email               VARCHAR(63) NOT NULL
);
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (1,'Luxury Oasis Resort',4.8,'Overlooking the crystal-clear waters of the Caribbean, this luxury resort offers opulent villas, world-class dining, and endless entertainment.','Free to cancel within 24 hours','1-800-555-1234','luxuryoasis@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (2,'City Center Boutique Hotel',4.6,'Nestled in the heart of downtown, this boutique hotel combines modern design with historic charm, perfect for business travelers and tourists alike.','Flexible cancellation up to 48 hours before check-in','1-800-555-1235','citycenter@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (3,'Serenity Hills Resort',4.7,'Escape to this peaceful mountain retreat with stunning views, cozy cabins, and a wide range of outdoor activities.','Non-refundable if canceled within 24 hours','1-800-555-1236','serenityhills@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (4,'Palm Beach Paradise',4.9,'Experience luxury and relaxation on the pristine beaches of Palm Beach with private villas and 24/7 concierge service.','Free cancellation up to 7 days before arrival','1-800-555-1237','palmbeach@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (5,'Country Charm Inn',4.3,'A quaint bed and breakfast in the countryside, offering a cozy atmosphere and breathtaking views of nature.','Non-refundable if canceled within 48 hours','1-800-555-1238','countrycharm@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (6,'Modern Skyline Hotel',4.4,'Savor the vibrant city life from the comfort of this modern hotel with panoramic city views and cutting-edge amenities.','Flexible cancellation up to 72 hours before arrival','1-800-555-1239','modernskyline@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (7,'Royal Palace Hotel',4.8,'Indulge in royal treatment at this historic hotel, complete with elegant rooms, fine dining, and exceptional service.','Non-refundable if canceled within 7 days','1-800-555-1240','royalpalace@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (8,'Sunset Beach Hotel',4.5,'Watch the sunset from your private balcony at this beachfront hotel offering cozy rooms and fun activities.','Free cancellation up to 48 hours before arrival','1-800-555-1241','sunsetbeach@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (9,'Lakeside Retreat',4.2,'A peaceful getaway on the shores of a serene lake, perfect for nature lovers and those seeking relaxation.','Non-refundable if canceled within 72 hours','1-800-555-1242','lakeside@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (10,'Metro Central Hotel',4.1,'Conveniently located in the city center, this hotel is ideal for business travelers with easy access to public transport.','Flexible cancellation up to 24 hours before arrival','1-800-555-1243','metrocentral@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (11,'Desert Oasis Hotel',4.6,'Experience the beauty of the desert at this luxurious hotel with stunning architecture and authentic cultural experiences.','Free cancellation up to 7 days before arrival','1-800-555-1244','desertoasis@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (12,'Villa del Lago',4.7,'A collection of stunning villas on the shores of a picturesque lake, offering privacy and luxury for your getaway.','Non-refundable if canceled within 48 hours','1-800-555-1245','villadelago@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (13,'Grand City Hotel',4.4,'A grand hotel in the heart of the city, offering opulent rooms, fine dining, and a world-class spa.','Flexible cancellation up to 7 days before arrival','1-800-555-1246','grandcity@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (14,'Holiday Haven Hotel',4.3,'A family-friendly hotel with a wide range of activities and spacious rooms for a fun-filled vacation.','Free cancellation up to 48 hours before arrival','1-800-555-1247','holidayhaven@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (15,'Mountain View Lodge',4.5,'Savor the fresh mountain air at this lodge offering cozy rooms, breathtaking views, and outdoor adventures.','Non-refundable if canceled within 72 hours','1-800-555-1248','mountainview@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (16,'Coastal Breeze Hotel',4.2,'A charming hotel by the sea, perfect for a relaxing getaway with easy access to the beach.','Flexible cancellation up to 24 hours before arrival','1-800-555-1249','coastalbreeze@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (17,'Palace of Dreams Hotel',4.8,'Experience the magic of this historic hotel with its elegant rooms and world-class service.','Non-refundable if canceled within 7 days','1-800-555-1250','palaceofdreams@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (18,'Jungle Adventure Hotel',4.4,'Immersed in the heart of the rainforest, this eco-friendly hotel offers unique rooms and exciting adventures.','Free cancellation up to 48 hours before arrival','1-800-555-1251','jungleadventure@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (19,'Harbor Lights Hotel',4.6,'Watch the ships come in from your private balcony at this waterfront hotel with stunning views.','Non-refundable if canceled within 72 hours','1-800-555-1252','harborlights@example.com');
INSERT INTO hotels(hotel_id,name,rating,description,cancellation_policy,phone,email) VALUES (20,'Premium Suites Hotel',4.3,'A luxury hotel offering premium suites with high-end amenities and personalized service.','Flexible cancellation up to 7 days before arrival','1-800-555-1253','premiumsuites@example.com');
