CREATE TABLE hotels(
   hotel_id    INTEGER  NOT NULL PRIMARY KEY 
  ,room_number INTEGER  NOT NULL
  ,type        VARCHAR(255) NOT NULL
  ,max_guests  INTEGER  NOT NULL
  ,amenities   VARCHAR(255) NOT NULL
);
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (1,101,'Studio Apartment',2,'Free WiFi, Coffee Maker, MiniFridge, Microwave');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (1,102,'Studio Apartment',2,'Free WiFi, Coffee Maker, MiniFridge, Microwave');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (1,103,'Studio Apartment',2,'Free WiFi, Coffee Maker, MiniFridge, Microwave');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (1,104,'Studio Apartment',2,'Free WiFi, Coffee Maker, MiniFridge, Microwave');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (2,201,'Executive Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (2,202,'Executive Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (2,203,'Executive Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (2,204,'Executive Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (3,301,'Queen Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (3,302,'Queen Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (3,303,'Queen Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (3,304,'Queen Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (4,401,'Presidential Suite',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (4,402,'Presidential Suite',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (4,403,'Presidential Suite',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (4,404,'Presidential Suite',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (5,501,'Double Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Eco-Friendly Products');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (5,502,'Double Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Eco-Friendly Products');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (5,503,'Double Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Eco-Friendly Products');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (5,504,'Double Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Eco-Friendly Products');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (6,601,'Beachfront Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (6,602,'Beachfront Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (6,603,'Beachfront Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (6,604,'Beachfront Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (7,701,'King Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, City View');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (7,702,'King Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, City View');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (7,703,'King Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, City View');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (7,704,'King Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, City View');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (8,801,'Deluxe Room',2,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Mountain View, Fireplace');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (8,802,'Deluxe Room',2,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Mountain View, Fireplace');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (8,803,'Deluxe Room',2,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Mountain View, Fireplace');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (8,804,'Deluxe Room',2,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Mountain View, Fireplace');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (9,901,'Imperial Suite',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (9,902,'Imperial Suite',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (9,903,'Imperial Suite',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (9,904,'Imperial Suite',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (10,1001,'Spa Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Spa Access, Massage Services');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (10,1002,'Spa Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Spa Access, Massage Services');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (10,1003,'Spa Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Spa Access, Massage Services');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (10,1004,'Spa Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Spa Access, Massage Services');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (11,1101,'Villa Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Private Pool, Garden Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (11,1102,'Villa Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Private Pool, Garden Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (11,1103,'Villa Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Private Pool, Garden Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (11,1104,'Villa Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Private Pool, Garden Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (12,1201,'Premium Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (12,1202,'Premium Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (12,1203,'Premium Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (12,1204,'Premium Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (13,1301,'Cozy Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Fireplace');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (13,1302,'Cozy Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Fireplace');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (13,1303,'Cozy Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Fireplace');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (13,1304,'Cozy Room',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Fireplace');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (14,1401,'Grand Suite',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (14,1402,'Grand Suite',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (14,1403,'Grand Suite',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (14,1404,'Grand Suite',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (15,1501,'Harmony Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Yoga Studio Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (15,1502,'Harmony Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Yoga Studio Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (15,1503,'Harmony Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Yoga Studio Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (15,1504,'Harmony Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Yoga Studio Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (16,1601,'Oceanfront Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (16,1602,'Oceanfront Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (16,1603,'Oceanfront Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (16,1604,'Oceanfront Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (17,1701,'Country Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Garden Access, Fireplace');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (17,1702,'Country Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Garden Access, Fireplace');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (17,1703,'Country Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Garden Access, Fireplace');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (17,1704,'Country Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Garden Access, Fireplace');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (18,1801,'Skyline Suite',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Skyline View, Fitness Center Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (18,1802,'Skyline Suite',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Skyline View, Fitness Center Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (18,1803,'Skyline Suite',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Skyline View, Fitness Center Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (18,1804,'Skyline Suite',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Skyline View, Fitness Center Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (19,1901,'Sunset Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (19,1902,'Sunset Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (19,1903,'Sunset Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (19,1904,'Sunset Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (20,2001,'Loft Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, City View, Modern Design');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (20,2002,'Loft Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, City View, Modern Design');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (20,2003,'Loft Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, City View, Modern Design');
INSERT INTO hotels(hotel_id,room_number,type,max_guests,amenities) VALUES (20,2004,'Loft Suite',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, City View, Modern Design');
