CREATE TABLE rooms(
   hotel_id    INTEGER  NOT NULL
  ,room_number INTEGER  NOT NULL
  ,type        VARCHAR(255) NOT NULL
  ,max_guests  INTEGER  NOT NULL
  ,amenities   VARCHAR(255) NOT NULL
  ,price       INTEGER  NOT NULL
  ,PRIMARY KEY(hotel_id,room_number)
);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (1,101,'Double Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Microwave',40341);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (1,102,'Double Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Microwave',65209);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (1,103,'Double Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Microwave',72783);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (1,104,'Double Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Microwave',84251);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (2,101,'Deluxe Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access',58392);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (2,102,'Deluxe Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access',62207);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (2,103,'Deluxe Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access',75768);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (2,104,'Deluxe Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access',109692);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (3,101,'Double Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer',84816);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (3,102,'Double Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer',90151);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (3,103,'Double Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer',95657);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (3,104,'Double Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer',97318);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (4,101,'Deluxe Bedroom',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services',35374);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (4,102,'Deluxe Bedroom',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services',79712);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (4,103,'Deluxe Bedroom',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services',83444);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (4,104,'Deluxe Bedroom',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services',99688);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (5,101,'Single Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Eco-Friendly Products',36356);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (5,102,'Single Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Eco-Friendly Products',45075);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (5,103,'Double Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Eco-Friendly Products',49058);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (5,104,'Double Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Eco-Friendly Products',82085);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (6,101,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access',49897);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (6,102,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access',64265);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (6,103,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access',95304);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (6,104,'Deluxe Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access',100723);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (7,101,'Single Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, City View',46643);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (7,102,'Single Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, City View',71579);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (7,103,'Premium Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, City View',87906);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (7,104,'Premium Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, City View',96471);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (8,101,'Classic Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Mountain View, Fireplace',50762);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (8,102,'Deluxe Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Mountain View, Fireplace',90287);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (8,103,'Single Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Mountain View, Fireplace',98860);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (8,104,'Single Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Mountain View, Fireplace',104386);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (9,101,'Deluxe Bedroom',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services',51059);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (9,102,'Deluxe Bedroom',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services',56595);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (9,103,'Deluxe Bedroom',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services',58266);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (9,104,'Deluxe Bedroom',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services',71833);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (10,101,'Single Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Spa Access, Massage Services',72535);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (10,102,'Single Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Spa Access, Massage Services',75293);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (10,103,'Single Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Spa Access, Massage Services',75803);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (10,104,'Single Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Spa Access, Massage Services',94468);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (11,101,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Private Pool, Garden Access',40336);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (11,102,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Private Pool, Garden Access',46441);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (11,103,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Private Pool, Garden Access',49979);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (11,104,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Private Pool, Garden Access',66940);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (12,101,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access',35330);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (12,102,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access',87811);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (12,103,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access',88405);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (12,104,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access',89293);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (13,101,'Single Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Fireplace',37044);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (13,102,'Single Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Fireplace',51458);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (13,103,'Single Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Fireplace',80408);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (13,104,'Single Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Hairdryer, Fireplace',95186);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (14,101,'Deluxe Bedroom',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services',37106);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (14,102,'Deluxe Bedroom',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services',104513);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (14,103,'Deluxe Bedroom',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services',105638);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (14,104,'Deluxe Bedroom',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Fitness Center Access, Spa Services',108620);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (15,101,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Yoga Studio Access',73914);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (15,102,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Yoga Studio Access',96368);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (15,103,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Yoga Studio Access',101262);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (15,104,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Balcony, Yoga Studio Access',102523);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (16,101,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access',62700);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (16,102,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access',73345);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (16,103,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access',73620);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (16,104,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access',81027);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (17,101,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Garden Access, Fireplace',44066);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (17,102,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Garden Access, Fireplace',78182);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (17,103,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Garden Access, Fireplace',80450);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (17,104,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Garden Access, Fireplace',92642);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (18,101,'Deluxe Bedroom',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Skyline View, Fitness Center Access',35712);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (18,102,'Deluxe Bedroom',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Skyline View, Fitness Center Access',73262);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (18,103,'Deluxe Bedroom',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Skyline View, Fitness Center Access',80019);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (18,104,'Deluxe Bedroom',6,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Skyline View, Fitness Center Access',95273);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (19,101,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access',35445);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (19,102,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access',39703);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (19,103,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access',70032);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (19,104,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Beach Access, Pool Access',90399);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (20,101,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, City View, Modern Design',56191);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (20,102,'Double Bedroom',4,'Free WiFi, Coffee Maker, MiniFridge, Microwave, City View, Modern Design',72110);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (20,103,'Single Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Microwave, City View, Modern Design',98773);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (20,104,'Single Bedroom',2,'Free WiFi, Coffee Maker, MiniFridge, Microwave, City View, Modern Design',104738);
INSERT INTO rooms(hotel_id,room_number,type,max_guests,amenities,price) VALUES (42,101,'Guesthouse',10,'Free WiFi, Coffee Maker, MiniFridge, Microwave, Oven, Sauna',133545);
